MQ.Routing={};
MQ.Routing.Directions=L.Class.extend({includes:L.Mixin.Events,options:{key:null,layer:null},initialize:function(a){MQ.mapConfig.setAPIKey(this.options);L.setOptions(this,a)},route:function(a){if(50<a.locations.length)this.fire("error",{info:{statusCode:-999,description:"Too many locations, MAX=50"}});else{a=this._checkShapeFormat(a);this.noTrim||(a.locations=this._trimLocations(a.locations));var b="route?key="+this.options.key;a.options.ambiguities&&(delete a.options.ambiguities,b+="&ambiguities=ignore");
var b=b+("&json="+MQ.util.stringifyJSON(a)),c=this;MQ.mapConfig.ready(function(){MQ.util.doJSONP(MQ.mapConfig.getConfig("directionsAPI")+b,{},L.Util.bind(c._onResult,c))})}},optimizedRoute:function(a){a=this._checkShapeFormat(a);this.noTrim||(a.locations=this._trimLocations(a.locations));var b="optimizedroute?key="+this.options.key,b=b+("&json="+MQ.util.stringifyJSON(a)),c=this;MQ.mapConfig.ready(function(){MQ.util.doJSONP(MQ.mapConfig.getConfig("directionsAPI")+b,{},L.Util.bind(c._onResult,c))})},
routeShape:function(a){a=this._checkShapeFormat(a);url="routeshape?key="+this.options.key;url+="&json="+MQ.util.stringifyJSON(a);var b=this;MQ.mapConfig.ready(function(){MQ.util.doJSONP(MQ.mapConfig.getConfig("directionsAPI")+url,{},L.Util.bind(b._onResult,b))})},dragRoute:function(a){a=this._checkShapeFormat(a);this.noTrim||(a.locations=this._trimLocations(a.locations));var b="dragroute?key="+this.options.key,b=b+("&json="+MQ.util.stringifyJSON(a)),c=this;MQ.mapConfig.ready(function(){MQ.util.doJSONP(MQ.mapConfig.getConfig("directionsAPI")+
b,{},L.Util.bind(c._onResult,c))})},routeMatrix:function(a){var b="routematrix?key="+this.options.key,b=b+("&json="+MQ.util.stringifyJSON(a)),c=this;MQ.mapConfig.ready(function(){MQ.util.doJSONP(MQ.mapConfig.getConfig("directionsAPI")+b,{},L.Util.bind(c._onResult,c))})},_checkShapeFormat:function(a){if(a.options&&a.options.shapeFormat&&""!=a.options.shapeFormat)return this.shapeFormat=a.options.shapeFormat,a;a.options||(a.options={});a.options.shapeFormat||(a.options.shapeFormat="cmp6");return a},
_onResult:function(a){if(!a||!a.route||a.info&&a.info.messages&&0<a.info.messages.length){var b=null;a&&a.info&&(b={code:a.info.statuscode,response:a},a.info.messages&&0<a.info.messages.length&&(b.message=a.info.messages[0]));this.fire("error",b)}else this.fire("success",this.decompress(a))},_trimLocations:function(a){if(a&&!(1>a.length)){for(var b,c=0,d=[];c<a.length;c++)(b=a[c])&&b.linkId?d.push({linkId:b.linkId,latLng:{lat:b.latLng.lat,lng:b.latLng.lng},type:b.type}):d.push(b);return d}},decompress:function(a){if(a&&
a.route&&a.route.shape&&a.route.shape.shapePoints&&a.route.options&&("cmp"==a.route.options.shapeFormat||"cmp6"==a.route.options.shapeFormat)){var b=a.route.shape.shapePoints,c=a.route.alternateRoutes,d=b.length,e=0,h=0,k=0,m=[];try{for(;e<d;){var l,f=0,g=0;do l=b.charCodeAt(e++)-63,g|=(l&31)<<f,f+=5;while(32<=l);h+=g&1?~(g>>1):g>>1;g=f=0;do l=b.charCodeAt(e++)-63,g|=(l&31)<<f,f+=5;while(32<=l);k+=g&1?~(g>>1):g>>1;"cmp"==a.route.options.shapeFormat?m.push(new L.LatLng(1E-5*h,1E-5*k)):m.push(new L.LatLng(1E-6*
h,1E-6*k))}}catch(n){}a.route.shape.shapePoints=m}if(c)for(b=0;b<c.length;b++)this.decompress(c[b]);return a}});MQ.routing={};MQ.routing.directions=function(a){null==a&&(a={});!a.key&&MQ.KEY&&(a.key=MQ.KEY);return new MQ.Routing.Directions(a)};MQ.util.loadCSS(".mq-ribbon-popup .leaflet-popup-tip-container{display: none;} .mq-ribbon-popup .leaflet-popup-content-wrapper{border-radius:6px;} .mq-ribbon-popup .leaflet-popup-content-wrapper .leaflet-popup-content{margin:3px 6px;font-size:11px;}");
MQ.Routing.Ribbon=L.LayerGroup.extend({includes:L.Mixin.Events,_state:"none",options:{draggable:!0,dragMarker:{weight:1,color:"#000000",fill:!0,fillColor:"#ffffff",opacity:0.9,fillOpacity:0.9}},initialize:function(a){L.setOptions(this,a);L.LayerGroup.prototype.initialize.call(this,a);this._polyline=new L.Polyline([],{smoothFactor:0,noClip:!0});this.addLayer(this._polyline);a={closeButton:!1,zoomAnimation:!1,autoPan:!1,className:"mq-ribbon-popup",offset:new L.Point(0,-20)};this._dragPopup=L.popup(a);
this._dragMarker=new L.CircleMarker(new L.LatLng(0,0),this.options.dragMarker);this._dragMarker.bindPopup(this._dragPopup)},onAdd:function(a){L.LayerGroup.prototype.onAdd.call(this,a);this.options.draggable&&(this._polyline.on("mouseover",this._onPathMouseOver,this),this._polyline.on("mousemove",this._onPathMouseMove,this),this._polyline.on("mouseout",this._onPathMouseOut,this),L.Browser.touch&&(L.DomEvent.on(this._polyline._container,"touchstart",this._onDragStart,this),L.DomEvent.on(this._polyline._container,
"touchmove",this._onTouchMove,this),L.DomEvent.on(this._polyline._container,"touchend",this._onDragEnd,this),L.DomEvent.on(this._polyline._container,"touchcancel",this._onDragEnd,this)),this._dragMarker.on("mouseover",this._onMarkerMouseOver,this),this._dragMarker.on("mouseout",this._onMarkerMouseOut,this),this._dragMarker.on("mousedown",this._onDragStart,this))},onRemove:function(a){L.LayerGroup.prototype.onRemove.call(this,a);this.options.draggable&&(this._polyline.off("mouseover",this._onPathMouseOver,
this),this._polyline.off("mousemove",this._onPathMouseMove,this),this._polyline.off("mouseout",this._onPathMouseOut,this))},setLatLngs:function(a){this._polyline.setLatLngs(a)},setPathStyle:function(a){this._polyline.setStyle(a);this._dragMarker.setRadius(a.weight/2)},_clearCancelInterval:function(){this._cancelInterval&&(window.clearInterval(this._cancelInterval),this._cancelInterval=null)},hideDragMarker:function(){this._clearCancelInterval();"drag"==this.state&&this._map&&(this._map.off("mousemove",
this._onDrag,this),this._map.off("mouseup",this._onDragEnd,this));this._state="none";this._map&&this.hasLayer(this._dragMarker)&&this.removeLayer(this._dragMarker)},closestLayerPoint:function(a){for(var b=Infinity,c=this._polyline._parts,d,e,h=null,k=0,m=c.length;k<m;k++)for(var l=c[k],f=1,g=l.length;f<g;f++){d=l[f-1];e=l[f];var n=L.LineUtil._sqClosestPointOnSegment(a,d,e,!0);n<b&&(b=n,h=L.LineUtil._sqClosestPointOnSegment(a,d,e),h.partIndex=f-1)}h&&(h.distance=Math.sqrt(b));return h},setHoverMessage:function(a){this._dragPopup.setContent(a)},
getBounds:function(){return this._polyline?this._polyline.getBounds():null},_onPathMouseOver:function(a){this._clearCancelInterval();"none"==this._state&&(this._state="hover",this.addLayer(this._dragMarker),this._dragMarker.openPopup(),this._onPathMouseMove(a))},_onPathMouseOut:function(a){"hover"==this._state&&(this._clearCancelInterval(),this._cancelInterval=window.setInterval(L.Util.bind(this.hideDragMarker,this),333))},_onPathMouseMove:function(a){if("hover"==this._state){a=this.closestLayerPoint(a.layerPoint);
var b=this._map.layerPointToLatLng(a);this._dragShapePointIndex=a.partIndex;this._dragMarker.setLatLng(b);this._dragPopup.setLatLng(b)}},_onMarkerMouseOver:function(a){this._clearCancelInterval()},_onMarkerMouseOut:function(a){"hover"==this._state&&(this._cancelInterval=window.setInterval(L.Util.bind(this.hideDragMarker,this),333))},_onDragStart:function(a){if("drag"!=this._state){this._state="drag";L.DomEvent.stop(a);if(L.Browser.touch){var b=this.closestLayerPoint(this._map.mouseEventToLayerPoint(a));
a.dragShapePointIndex=b.partIndex}else a.dragShapePointIndex=this._dragShapePointIndex,this._map.on("mousemove",this._onDrag,this),this._map.on("mouseup",this._onDragEnd,this);this.fire("dragstart",a)}},_onTouchMove:function(a){if(!(a.touches&&1<a.touches.length)){var b=a.touches&&1===a.touches.length?a.touches[0]:a;new L.Point(b.clientX,b.clientY);L.DomEvent.preventDefault(a);b=this._map.mouseEventToLatLng(a);a.latlng=b;this._onDrag(a)}},_onDrag:function(a){"drag"==this._state&&(this._dragMarker.setLatLng(a.latlng),
this._dragPopup.setLatLng(a.latlng),this.fire("drag",a))},_onDragEnd:function(a){"drag"==this._state&&(this.hideDragMarker(),this.fire("dragend",a))}});MQ.Routing.RouteLayer=L.LayerGroup.extend({ribbonOverscanFactor:5,dragIntervalMs:333,customizeRibbon:function(a){var b={color:"#0000ee",opacity:0.6,weight:5};this.options.ribbonOptions&&this.options.ribbonOptions.ribbonDisplay&&(b=L.Util.extend(b,this.options.ribbonOptions.ribbonDisplay));a.setPathStyle(b)},customizeRibbonAtZoom:function(a,b){var c=this.options.ribbonOptions.widths[b-2];c&&c!=a._polyline.options.weight&&a.setPathStyle({weight:c})},createStopMarker:function(a,b){var c=L.icon({iconUrl:MQ.mapConfig.getConfig("iconPath")+
"/icons/stop.png?text="+String.fromCharCode(b-1+65),iconSize:[22,28],iconAnchor:[11,28],popupAnchor:[0,-28]});return L.marker(a.latLng,{icon:c,draggable:this.options.draggable}).addTo(this._map)},createViaMarker:function(a){var b=L.icon({iconUrl:MQ.mapConfig.getConfig("iconPath")+"/icons/via.png",iconSize:[11,11],iconAnchor:[5,5],popupAnchor:[0,-5]});return L.marker(a.latLng,{icon:b,draggable:this.options.draggable}).addTo(this._map)},customizeMarker:function(a){},virtualMapState:function(a){return{center:a.getCenter(),
width:Math.round(this.ribbonOverscanFactor*a.getSize().x),height:Math.round(this.ribbonOverscanFactor*a.getSize().y),scale:MQ.mapConfig.getScale(a.getZoom())}},recomputeChangedRoute:function(a){var b={};this.routeData&&(b=this.routeData.options,this.routeData=null);a={mapState:this.virtualMapState(this._map),locations:a,options:b};this.directions.route(a)},options:{key:null,draggable:!0,fitBounds:!1,routeOptions:{},ribbonOptions:{draggable:!0,widths:[10,10,10,10,9,8,7,7,7,6,6,6,6,7,8,9,10]}},initialize:function(a){MQ.mapConfig.setAPIKey(this.options);
a&&a.ribbonOptions&&(a.ribbonOptions=L.extend({},this.options.ribbonOptions,a.ribbonOptions));L.setOptions(this,a);L.LayerGroup.prototype.initialize.call(this,a);this.directions=this.options.directions?this.options.directions:new L.Routing.Directions;this.directions.on("success",this._onDirectionsSuccess,this);this.directions.on("error",this._onDirectionsError,this)},onAdd:function(a){L.LayerGroup.prototype.onAdd.call(this,a);a.on("move",this._validateMap,this);a.on("moveend",this._validateMap,this);
a.on("zoomend",this._validateMap,this);this.state="none"},onRemove:function(a){this._stopDragTimer();a.off("move",this._validateMap,this);a.off("moveend",this._validateMap,this);a.off("zoomend",this._validateMap,this);L.LayerGroup.prototype.onRemove.call(this,a)},_onDirectionsSuccess:function(a){this.routeData?a&&(a.route&&a.route.shape)&&this._routeShapeCallback(a):(this.setRouteData(a.route),this.options.fitBounds&&!this._fitBoundsFirstTime&&(this._fitBoundsFirstTime=!1,this.fitBounds()));if(this._lastDragRequest&&
(this._lastDragRequest=null,a&&a.route&&a.route.shape&&a.route.shape.shapePoints)){this._lastDragLocations=a.route.locations;for(var b=0;b<a.route.locations.length;b++){var c=a.route.locations[b];c.dragPoint&&this._setHoverMessage(a.route,c)}}this._nextDragRequest&&this._dispatchDragRequest()},_onDirectionsError:function(a){a&&console.log("Error loading directions: "+a.message)},_setHoverMessage:function(a,b){var c=a.time,d="",e=a.distance.toFixed(2),h="M"==a.options.unit.toUpperCase()?"mi":"km",
k=Math.floor(c/86400).toFixed(),m=Math.floor(c/3600%24).toFixed(),c=Math.floor(c/60%60).toFixed();0!=k&&(d+=k+"d ");0!=m&&(d+=m+"h ");0!=c&&(d+=c+"m ");this.ribbon.setHoverMessage(b.street+" ("+e+h+", "+d+")")},setRouteData:function(a){this._clear();this.routeData=a;try{a&&this._construct(a,a.mapState,a.shape)}catch(b){throw this._clear(),b;}},getBounds:function(){return this.routeData&&this.routeData.boundingBox&&this.routeData.boundingBox.ul?new L.LatLngBounds(new L.LatLng(this.routeData.boundingBox.lr.lat,
this.routeData.boundingBox.ul.lng),new L.LatLng(this.routeData.boundingBox.ul.lat,this.routeData.boundingBox.lr.lng)):null},fitBounds:function(){if(this._map&&this.routeData){var a=this.getBounds();a&&this._map.fitBounds(a)}},_validateMap:function(){if(this._ribbonInfo){var a=this._map.getPixelBounds();this._map.getZoom()==this._ribbonInfo.zoom&&this._ribbonInfo.bounds.contains(a)||(this.ribbon&&this.ribbon.dragPoi&&this.ribbon.hideDragPoi(),this._schedRibbonUpdate())}this._validateRibbonAttrs(this.ribbon)},
_validateRibbonAttrs:function(a){if(a){var b=this._map.getZoom();a._attrZoom!=b&&(this.customizeRibbonAtZoom(a,b),a._attrZoom=b)}},_clear:function(){this.state="none";this.clearLayers();this._ribbonInfo&&this._ribbonInfo.completion&&ribbonInfo.completion();this.ribbon=null},_construct:function(a,b,c){this.routeData=a;this.ribbon=new MQ.Routing.Ribbon(this.options.ribbonOptions);this.ribbon.options.draggable&&(this.ribbon.setHoverMessage("Click To Drag"),this.ribbon.on("dragstart",this._onRibbonDragStart,
this),this.ribbon.on("drag",this._onRibbonDrag,this),this.ribbon.on("dragend",this._onRibbonDragEnd,this));this.addLayer(this.ribbon);this.customizeRibbon(this.ribbon);this._validateRibbonAttrs(this.ribbon);this.state="show";b&&c&&b.zoom==this._map.getZoom()?(this._ribbonInfo={loaded:!0,shapeResponse:c},this._updateRibbonInfo(),this.ribbon.setLatLngs(c.shapePoints),this.ribbon.shapeResponse=c,this._validateMap()):this._schedRibbonUpdate();a.locations&&this._constructLocations(a.locations)},_constructLocations:function(a){var b,
c=0,d,e;for(b=0;b<a.length;b++){d=a[b];switch((d.type||"").toUpperCase()){case "S":e=this.createStopMarker(d,++c);e.stopNumber=c;break;case "V":e=this.createViaMarker(d)}e&&(d.address&&d.address.latLng&&(d.latLng=d.address.latLng),e.location=d,e.locationIndex=b,this.options.draggable&&(e.on("drag",this._onMarkerDrag,this),e.on("dragend",this._onMarkerDragEnd,this)),this.customizeMarker(e),this.addLayer(e))}},_routeShapeCallback:function(a){if(a&&a.route&&a.route.shape){a=a.route.shape;var b=this._ribbonInfo;
b.loaded=!0;b.completion=null;b.shapeResponse=a;L.Util.isArray(a.shapePoints)&&this.ribbon.setLatLngs(a.shapePoints);this.ribbon.shapeResponse=a}else this._ribbonInfo=null},_schedRibbonUpdate:function(){if("show"==this.state){var a=this.virtualMapState(this._map);this._ribbonInfo={loaded:!1};this._updateRibbonInfo();this._ribbonInfo.completion=this.directions.routeShape({sessionId:this.routeData.sessionId,mapState:a});return this._ribbonInfo}},_updateRibbonInfo:function(){var a=this._map.getPixelBounds(),
b=a.getSize().x/2,c=a.getSize().y/2,a=a.min;a.x+=b;a.y+=c;b*=this.ribbonOverscanFactor;c*=this.ribbonOverscanFactor;this._ribbonInfo.bounds=new L.Bounds(new L.Point(a.x-b,a.y-c),new L.Point(a.x+b,a.y+c));this._ribbonInfo.zoom=this._map.getZoom()},_onRibbonDragStart:function(a){for(var b=0;b<this.ribbon.shapeResponse.legIndexes.length&&!(a.dragShapePointIndex<=this.ribbon.shapeResponse.legIndexes[b]);b++);this._dragLocationIndex=b},_onRibbonDrag:function(a){if("show"==this.state){for(var b=this.routeData.locations.slice(),
c=0;c<b.length;c++)b[c].dragPoint=!1;b.splice(this._dragLocationIndex,0,{latLng:a.latlng,gefId:0,dragPoint:!0,type:"v"});dragRouteRequest={options:this.routeData.options,locations:b,mapState:{center:this._map.getCenter(),width:Math.round(1.25*this._map.getSize().x),height:Math.round(1.25*this._map.getSize().y),scale:MQ.mapConfig.getScale(this._map.getZoom())}};this._queueDragRequest(dragRouteRequest)}},_onRibbonDragEnd:function(a){this.clearDragState();this._lastDragLocations&&this.recomputeChangedRoute(this._lastDragLocations)},
_onMarkerDrag:function(a){if("show"==this.state){for(var b=this.routeData.locations.slice(),c=0;c<this.routeData.locations.length;c++)b[c].dragPoint=!1;b[a.target.locationIndex]={dragPoint:!0,latLng:a.target.getLatLng(),gefId:0,type:b[a.target.locationIndex].type};dragRouteRequest={options:this.routeData.options,locations:b,mapState:{center:this._map.getCenter(),width:Math.round(1.25*this._map.getSize().x),height:Math.round(1.25*this._map.getSize().y),scale:MQ.mapConfig.getScale(this._map.getZoom())}};
this._queueDragRequest(dragRouteRequest)}},_onMarkerDragEnd:function(a){this.clearDragState();this._lastDragLocations&&this.recomputeChangedRoute(this._lastDragLocations)},clearDragState:function(){this._stopDragTimer();this.state="show"},_stopDragTimer:function(){this._clearDragInterval();this._nextDragRequest=this._lastDragRequest=null},_clearDragInterval:function(){this._dragIntervalId&&(window.clearInterval(this._dragIntervalId),this._dragIntervalId=null)},_queueDragRequest:function(a){this._clearDragInterval();
this._nextDragRequest=a;this._dragIntervalId=window.setInterval(L.Util.bind(this._dispatchDragRequest,this),this.options.dragIntervalMs)},_dispatchDragRequest:function(){!this._lastDragRequest&&this._nextDragRequest&&(this._clearDragInterval(),this._lastDragRequest=this._nextDragRequest,this.directions.dragRoute(this._nextDragRequest),this._nextDragRequest=null)}});MQ.routing.routeLayer=function(a){null==a&&(a={});!a.key&&MQ.KEY&&(a.key=MQ.KEY);return new MQ.Routing.RouteLayer(a)};

MQ.KEY=Key=mapquest_key;

MQPLUGINVERSION='1.0';
MQCONFIGNUMBER=1;
MQTILELOGGER="http://coverage.win.mqcdn.com/logger/v1/transaction?transaction=log&t={$type}&c={$cost1}&c2={$cost2}&s={$scale}&lat={$lat}&lng={$lng}&key={$key}&rand={$rand}";
MQCDN="http://api.mqcdn.com/";
MQDIRECTIONS="http://www.mapquestapi.com/directions/";
MQTRAFFIC="http://www.mapquestapi.com/traffic/";
MQGECOODE="http://www.mapquestapi.com/geocoding/";
MQCOPYRIGHT="http://coverage.win.mqcdn.com/coverage?projection=sm&format={$format}&loc={$lon1},{$lat1},{$lon2},{lat2}&zoom={$zoom}&cat={$category}";
MQTILEMAP="http://mtile0{$hostrange}.mqcdn.com/tiles/1.0.0/vy/map/{$z}/{$x}/{$y}.{$ext}";
MQTILEMAPEXT="jpg";
MQTILEHYB="http://mtile0{$hostrange}.mqcdn.com/tiles/1.0.0/vy/hyb/{$z}/{$x}/{$y}.{$ext}";
MQTILEHYBEXT="png";
MQTILESAT="http://mtile0{$hostrange}.mqcdn.com/tiles/1.0.0/vy/sat/{$z}/{$x}/{$y}.{$ext}";
MQTILESATEXT="jpg";
MQTILEHI=4;
MQTILELO=1;
MQICONS='http://icons.mqcdn.com/';
MQIMAGEPATH='http://content.mqcdn.com/winston-354/cdn/toolkit/lite/images/';

